### ISSUE TITLE
WeatherPi_TFT.py uses CrLf instead of LF

### ISSUE THREAD

**Issue by luiscantero** [LoveBootCaptain/WeatherPi_TFT#19]
The code does not run as a service, the file needs to be converted to use LF.

Current behavior:
$ sudo service WeatherPiTFT restart
$ sudo service WeatherPiTFT status
● WeatherPiTFT.service - LSB: WeatherPiTFT
   Loaded: loaded (/etc/init.d/WeatherPiTFT; generated)
   Active: active (exited) since Sat 2020-05-09 11:59:16 CEST; 10s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1266 ExecStart=/etc/init.d/WeatherPiTFT start (code=exited, status=0/SUCCESS)

Mai 09 11:59:16 piwetter systemd[1]: Starting LSB: WeatherPiTFT...
Mai 09 11:59:16 piwetter WeatherPiTFT[1266]: Starting system WeatherPiTFT daemon:.
Mai 09 11:59:16 piwetter systemd[1]: Started LSB: WeatherPiTFT.

**Comment by LoveBootCaptain** [comment]
belief me... my version of that file never saw a windows computer ;)
but to be sure i double checked and recomitted the to scripts with 

`git config --global core.autocrlf input`

enabled...

try this new version: https://github.com/LoveBootCaptain/WeatherPi_TFT/commit/4e5d2048fbc124aaa6642f1752b7d9fc8164710e

for me it always works on the Pi

```
pi@WeatherPiTFT:~/WeatherPi_TFT $ sudo service WeatherPiTFT status
● WeatherPiTFT.service - LSB: WeatherPiTFT
   Loaded: loaded (/etc/init.d/WeatherPiTFT; generated)
   Active: active (running) since Sat 2020-05-09 18:52:34 CEST; 5s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 5518 ExecStart=/etc/init.d/WeatherPiTFT start (code=exited, status=0/SUCCESS)
   Memory: 12.2M
   CGroup: /system.slice/WeatherPiTFT.service
           └─5525 /usr/bin/python3 /home/pi/WeatherPi_TFT/WeatherPi_TFT.py

Mai 09 18:52:33 WeatherPiTFT systemd[1]: Starting LSB: WeatherPiTFT...
Mai 09 18:52:34 WeatherPiTFT WeatherPiTFT[5518]: Starting system WeatherPiTFT daemon:.
Mai 09 18:52:34 WeatherPiTFT systemd[1]: Started LSB: WeatherPiTFT.
```

kind regards
