### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by raspifun** [LoveBootCaptain/WeatherPi_TFT#46]
Hello I have tired this project on Raspi 0W2 and I have no idea what I'm doing wrong, it is just not working. I did follow the instuctions and I did try it many many times with headless and desktop version of OS and I have failed.  Please help if possible.

**Comment by accountForIssues** [comment]
Have you tested it on a Laptop or similar ? Have you tried to run it manually and see what error messages you get ?

I am currently testing this (on a Raspi 4 with HDMI) and all I had to do was:
- Created and activated a virtual environment.
- Cloned the repo.
- Installed the requirements.
- Copied and edited the config.
- Run `python ./WeatherPiTFT.py`

**Comment by VentoFahrer** [comment]
Not working for me too. I followed step for step the instructions.

`pi@raspberrypi:~/WeatherPi_TFT $ sudo python ./WeatherPiTFT.py
  File "./WeatherPiTFT.py", line 95
    HEADERS = {'X-Api-Key': f'{config["MOCKSERVER_API_KEY"]}'}
                                                            ^
SyntaxError: invalid syntax
`

**Comment by LoveBootCaptain** [comment]
> Not working for me too. I followed step for step the instructions.
> 
> `pi@raspberrypi:~/WeatherPi_TFT $ sudo python ./WeatherPiTFT.py
> 
> File "./WeatherPiTFT.py", line 95
> 
> ```
> HEADERS = {'X-Api-Key': f'{config["MOCKSERVER_API_KEY"]}'}
>                                                         ^
> ```
> 
> SyntaxError: invalid syntax `

Maybe just use python3 ?

**Comment by LoveBootCaptain** [comment]
> Hello I have tired this project on Raspi 0W2 and I have no idea what I'm doing wrong, it is just not working. I did follow the instuctions and I did try it many many times with headless and desktop version of OS and I have failed. Please help if possible.

Since I don't know how you use it, I have not idea why it is not working for you :(

**Comment by LoveBootCaptain** [comment]
> Have you tested it on a Laptop or similar ? Have you tried to run it manually and see what error messages you get ?
> 
> I am currently testing this (on a Raspi 4 with HDMI) and all I had to do was:
> 
> * Created and activated a virtual environment.
> * Cloned the repo.
> * Installed the requirements.
> * Copied and edited the config.
> * Run `python ./WeatherPiTFT.py`

This is the way... Maybe try python3 instead of just python if you are still using python2 for whatever reason.

Thx for helping out here... It is it good strategy to figure out things that may not work the first try...

**Comment by golfer83** [comment]
> > Not working for me too. I followed step for step the instructions.
> > `pi@raspberrypi:~/WeatherPi_TFT $ sudo python ./WeatherPiTFT.py
> > File "./WeatherPiTFT.py", line 95
> > ```
> > HEADERS = {'X-Api-Key': f'{config["MOCKSERVER_API_KEY"]}'}
> >                                                         ^
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > SyntaxError: invalid syntax `
> 
> Maybe just use python3 ?

yes python3 ....
