### ISSUE TITLE
German words in English language setting

### ISSUE THREAD

**Issue by HWHardsoft** [LoveBootCaptain/WeatherPi_TFT#8]
Hi,
when I tried to set the language in the config.json to "en" some text output is still in German

![IMG_20200502_115913](https://user-images.githubusercontent.com/3049858/80861114-b9d01580-8c6c-11ea-9efa-ff6fa8bdfed4.jpg)

**Comment by LoveBootCaptain** [comment]
Hi,

the word 'Regen' is hardcoded.
there are 3 hardcoded german words in the code
'Regen' - rain
'Schnee' - snow
'Niederschlag' - Precipitation
based on the kind of precipitation rain or snow is shown... if no precipitation is in the forecast there will be shown: 0% Precipitation

maybe it is good to but this 3 words in the config.json for own translation?
what would you say?

kind regards

**Comment by LoveBootCaptain** [comment]
I fixed this in the theme.json. there you can find the strings for own localisation.
https://github.com/LoveBootCaptain/WeatherPi_TFT/commit/80143a29195544df9efbe630044b21df81291048
